import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cookieToInitialState } from "wagmi";
import { headers } from "next/headers";
import { config } from "@/config";
import Web3ModalProvider from "@/context";
import Navbar from "@/components/Navbar";
const inter = Inter({ subsets: ["latin"] });
import { MapProvider } from "./context/MapContext";
export const metadata: Metadata = {
  title: "DeciReport",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));
  return (
    <html lang="en">
      <body className="radialGradient">
        <Web3ModalProvider initialState={initialState}>
          <Navbar />
          <MapProvider>{children}</MapProvider>
        </Web3ModalProvider>
      </body>
    </html>
  );
}
