/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  MessageHashUtils,
  MessageHashUtilsInterface,
} from "../../../../../@openzeppelin/contracts/utils/cryptography/MessageHashUtils";

const _abi = [
  {
    inputs: [],
    name: "ERC5267ExtensionsNotSupported",
    type: "error",
  },
] as const;

const _bytecode =
  "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea26469706673582212203f7e025c34e9de8a4c2a7d891c33911b00a3f3ddf5d2d910837b82ffe1e3b75c64736f6c63430008180033";

type MessageHashUtilsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MessageHashUtilsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MessageHashUtils__factory extends ContractFactory {
  constructor(...args: MessageHashUtilsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MessageHashUtils & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MessageHashUtils__factory {
    return super.connect(runner) as MessageHashUtils__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MessageHashUtilsInterface {
    return new Interface(_abi) as MessageHashUtilsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MessageHashUtils {
    return new Contract(address, _abi, runner) as unknown as MessageHashUtils;
  }
}
